substitutions:
  name: apollo-mtr-1
  version: "26.3.2.1"
  device_description: ${name} made by Apollo Automation - version ${version}.

esp32:
  variant: esp32c3
  flash_size: 4MB
  framework:
    type: esp-idf

captive_portal:

web_server:
  port: 80
  version: 3

i2c:
  sda: GPIO1
  scl: GPIO0
  id: bus_a

uart:
  id: uart_bus
  tx_pin:
    number: GPIO21
    mode:
      input: true
      pullup: true
  rx_pin:
    number: GPIO20
    mode:
      input: true
      pullup: true
  rx_buffer_size: 1024
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_bus

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Timeout"
    zone_1:
      x1:
        name: Zone-1 X1
      y1:
        name: Zone-1 Y1
      x2:
        name: Zone-1 X2
      y2:
        name: Zone-1 Y2
    zone_2:
      x1:
        name: Zone-2 X1
      y1:
        name: Zone-2 Y1
      x2:
        name: Zone-2 X2
      y2:
        name: Zone-2 Y2
    zone_3:
      x1:
        name: Zone-3 X1
      y1:
        name: Zone-3 Y1
      x2:
        name: Zone-3 X2
      y2:
        name: Zone-3 Y2

output:
  - platform: ledc
    pin: GPIO10
    id: buzzer
rtttl:
  output: buzzer

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      id: ld2450_presence
      name: "LD2450 Presence"

  - platform: status
    name: Online
    id: ink_ha_connected

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_1:
      x:
        name: Target-1 X
      y:
        name: Target-1 Y
    target_2:
      x:
        name: Target-2 X
      y:
        name: Target-2 Y
    target_3:
      x:
        name: Target-3 X
      y:
        name: Target-3 Y
    zone_1:
      target_count:
        name: Zone-1 All Target Count
    zone_2:
      target_count:
        name: Zone-2 All Target Count
    zone_3:
      target_count:
        name: Zone-3 All Target Count

button:
  - platform: ld2450
    ld2450_id: ld2450_radar
    factory_reset:
      name: "Factory Reset LD2450"
      disabled_by_default: True
  
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

switch:
  - platform: factory_reset
    id: factory_reset_switch
    internal: true
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "LD2450 Bluetooth"
    multi_target:
      name: "Multi Target Tracking"
select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    baud_rate:
      name: "Baud rate"
      disabled_by_default: true
    zone_type:
      name: "Zone Type"

text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "LD2450 Firmware"
  - platform: template
    name: "Apollo Firmware Version"
    id: apollo_firmware_version
    update_interval: never
    entity_category: diagnostic
